lane :test do
  teams_card(
    workflow_url: 'https://your.logic.azure.com:443/workflows/1234567890',
    title: 'Notification Title',
    text: 'A new release is ready for testing!',
    image: 'https://raw.githubusercontent.com/fastlane/boarding/master/app/assets/images/fastlane.png',
    image_title: 'Fastlane',
    open_url: 'https://beta.itunes.apple.com/v1/app/_YOUR_APP_ID_',
    facts: [
      {
        'title' => 'Environment',
        'value' => 'Staging'
      },
      {
        'title' => 'Release',
        'value' => '1.0.3'
      }
    ]
  )
end
