# load variables from .env file in the root if it exists
if File.exist?('../.env')
  open('../.env', 'r').readlines.each do |l|
    kv = l.split('=')
    ENV[kv[0]] = kv[1].chomp
  end
end

lane :test do
  teams_card(
    workflow_url: ENV.fetch("TEAMS_MESSAGE_WORKFLOW_URL"),
    title: 'Notification Title',
    text: 'A new release is ready for testing!',
    image: 'https://raw.githubusercontent.com/fastlane/boarding/master/app/assets/images/fastlane.png',
    image_title: 'Fastlane',
    open_url: 'https://beta.itunes.apple.com/v1/app/_YOUR_APP_ID_',
    facts: [
      {
        'title' => 'Environment',
        'value' => 'Staging'
      },
      {
        'title' => 'Release',
        'value' => '1.0.3'
      }
    ]
  )
end

lane :custom do
  teams_card(
    workflow_url: "https://prod-130.westeurope.logic.azure.com:443/workflows/b61f4163876e46bd841ed3c19d9d9d3a/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=ajp4_dPErpjCZVdlM0vu_eiwjtPxpIZyMhaIH4HZtVc",
    custom_card: {
      "type" => "AdaptiveCard",
      "body" => [
        {
          "type" => "TextBlock",
          "text" => "Custom message content!",
          "wrap" => true
        }
      ],
      "$schema" => "http://adaptivecards.io/schemas/adaptive-card.json",
      "version" => "1.2"
    }
  )
end
